Chatroom/Models/ResponseHandler.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Chatroom.Models
{
    public class ResponseHandler
    {
        private int code;
        private string msg;

        public int Code
        {
            get
            {
                return code;
            }

            set
            {
                code = value;
            }
        }

        public string Msg
        {
            get
            {
                return msg;
            }

            set
            {
                msg = value;
            }
        }

        public ResponseHandler(int code, string msg)
        {
            Code = code;
            Msg = msg;
        }
    }
}

Chatroom/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Chatroom.Models
{
    public class User
    {
        private int id;
        private string email;
        private string passwrd;
        private string username;

        public int Id
        {
            get
            {
                return id;
            }

            set
            {
                id = value;
            }
        }

        public string Email
        {
            get
            {
                return email;
            }

            set
            {
                email = value;
            }
        }

        public string Passwrd
        {
            get
            {
                return passwrd;
            }

            set
            {
                passwrd = value;
            }
        }

        public string Username
        {
            get
            {
                return username;
            }

            set
            {
                username = value;
            }
        }
    }
}

Chatroom/Controllers/ChatController.cs
using Chatroom.Models;
using RabbitMQ.Client;
using Microsoft.AspNet.SignalR.Client;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.Configuration;
using System.Transactions;
using System.Web.Security;
using Chatroom.Helpers;
using Unity;

namespace Chatroom.Controllers
{
    public class ChatController : Controller
    {
        private readonly IDbHelper db;
        private readonly IMessageBroker obj;
        private readonly IBotHelper bot;

        public ChatController(IDbHelper dba, IMessageBroker obj, IBotHelper bot)
        {
            this.db = dba;
            this.obj = obj;
            this.bot = bot;
        }

        [Authorize]
        public ActionResult Index()
        {
            User authenticatedUser = db.GetUserById(Convert.ToInt32(ChatroomEncrypter.Decrypt(User.Identity.Name)));
            ViewData["Username"] = (authenticatedUser != null) ? authenticatedUser.Username : "";
            obj.suscribe();
            return View();
        }

        [Authorize]
        [HttpPost]
        public JsonResult SendMessage(string message)
        {
            if (!String.IsNullOrEmpty(message))
            {
                if (message.Contains("/stock="))
                {
                    bot.RequestStockQuotes(message);
                }
                else
                {
                    User authenticatedUser = db.GetUserById(Convert.ToInt32(ChatroomEncrypter.Decrypt(User.Identity.Name)));
                    if (obj.send(authenticatedUser.Username + " : " + message))
                    {
                        db.UpdateDatabasePost(message, authenticatedUser.Id);
                    }
                }
            }

            return Json(String.Empty);
        }
    }
}

Chatroom/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Chatroom.Models;
using Chatroom.Helpers;
using System.Web.Security;

namespace Chatroom.Controllers
{
    public class HomeController : Controller
    {
        private readonly IDbHelper db;

        public HomeController(IDbHelper dba)
        {
            this.db = dba;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult UserRegister(User usuario)
        {
            return Json(db.UserRegister(usuario));
        }

        [HttpPost]
        public JsonResult UserLogin(User usuario, string ReturnUrl = "/Chat/Index")
        {
            ResponseHandler isValid = db.UserValidate(usuario);
            if (isValid.Code.Equals(200))
            {
                FormsAuthentication.SetAuthCookie(ChatroomEncrypter.Encrypt(isValid.Msg), false);
            }
            return Json(isValid);
        }

        [HttpPost]
        public JsonResult UserLogOut()
        {
            try
            {
                FormsAuthentication.SignOut();
                return Json(new ResponseHandler(200, "OK"));
            }
            catch (Exception ex)
            {
                return Json(new ResponseHandler(500, ex.Message));
            }
        }
    }

}

Chatroom/Views/Chat/Index.cshtml
@{
    /**/

    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Chat Room</h2>
<br />
<br />
<div class="row">
    <div class="col-md-6 col-lg-6">
        <b>Username: </b><label id="lblUsername">@ViewData["Username"]</label>
    </div>
    <div class="col-md-6 col-lg-6">
        <button class="btn btn-warning pull-right" id="btnLogout"><i class="glyphicon glyphicon-log-out"></i> Log Out</button>
    </div>
    <div class="col-md-12 col-lg-12">
        <div style="height: 400px; overflow-y:scroll;" class="panel panel-default">
            <div class="panel-body">
                <ul id="chat"></ul>
            </div>
        </div>
    </div>
    <div class="col-md-12 col-lg-12">
        <div class="form-group input-group">
            <label for="txtMessage">New Message: </label>
            <input type="text" class="form-control" maxlength="500" placeholder="Message" id="txtMessage" name="txtMessage" />
        </div>
        <div class="form-group">
            <button class="btn btn-success" id="btnSend" name="btnSend">Send</button>
        </div>
    </div>
</div>

@section scripts {
    <script src="@Url.Content("~/Scripts/jquery.signalR-2.4.1.min.js")"></script>
    <script src="@Url.Content("~/signalr/hubs")"></script>
    <script>

    $(document).ready(function () {
        var pipe = [];

        var chat = $.connection.chatHub;

        chat.client.sendChat = function (msg) {
            pipe.push(msg);
            $("#chat").append("<li>" + msg + "</li>");
            if (pipe.length >= 51) {
                pipe.pop();
                $("#chat").find(':first-child').remove();
            }
        }

        $.connection.hub.start().done(function () {
            console.debug('Connected to ChatHub...');
        });

        $("#btnSend").click(function () {
            var message = $("#txtMessage").val();
            $("#txtMessage").val("").focus();

            $.ajax({
                type: "POST",
                contentType: "application/json; charset=utf-8",
                data: '{"message":"' + message + '"}',
                url: "@Url.Action("SendMessage")",
                dataType: "json",
                success: function (response) {

                },
                error: function (response) {

                }
            });
        });

        $("#btnLogout").click(function () {
            $.ajax({
                type: "POST",
                contentType: "application/json; charset=utf-8",
                data: '{}',
                url: "@Url.Action("UserLogOut", "Home")",
                dataType: "json",
                success: function (response) {
                    if (response.Code == 200) {
                        window.location.href = "@Url.Action("Index", "Home")";
                    }
                },
                error: function (response) {
                }
            });
        });

    });

    </script>

}

Chatroom/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Login Page";
}

<h3>Bienvenido a Chatroom by Daniel Carbajal Fernandez</h3>
<br />
<br />
<div class="container">
    <div class="row">
        <div class="col-md-6 col-lg-6 col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h5>Login Users</h5>
                    <div id="dvCorrectLogin" style="display: none;" class="alert alert-success">
                        <b>Success! </b><label id="lblMessageCorrectLogin"></label>
                    </div>
                    <div id="dvIncorrectLogin" style="display: none;" class="alert alert-danger">
                        <b>Error! </b><label id="lblMessageIncorrectLogin"></label>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12 col-lg-12">
                                <label for="txtEmailLogin">Email: </label>
                                <input type="text" value="" id="txtEmailLogin" name="txtEmailLogin" class="form-control" placeholder="Email" />
                            </div>
                            <div class="col-md-12 col-lg-12">
                                <label for="txtPasswordLogin">Password: </label>
                                <input type="password" value="" id="txtPasswordLogin" name="txtPasswordLogin" class="form-control" placeholder="Password" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <button id="btnLogin" name="btnLogin" class="btn btn-success">Log In !</button>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-6 col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h5>If you are new user, Register Here !</h5>
                    <div id="dvRegisterCorrect" style="display: none;" class="alert alert-success">
                        <b>Success! </b><label id="lblMessageCorrectRegister"></label>
                    </div>
                    <div id="dvRegisterIncorrect" style="display: none;" class="alert alert-danger">
                        <b>Error! </b><label id="lblMessageIncorrectRegister"></label>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12 col-lg-12">
                                <label for="txtEmail">Email: </label>
                                <input type="text" value="" id="txtEmail" name="txtEmail" class="form-control" placeholder="Email" />
                            </div>
                            <div class="col-md-12 col-lg-12">
                                <label for="txtUsername">Username: </label>
                                <input type="text" value="" id="txtUsername" name="txtUsername" class="form-control" placeholder="Username" />
                            </div>
                            <div class="col-md-12 col-lg-12">
                                <label for="txtPassword">Password: </label>
                                <input type="password" value="" id="txtPassword" name="txtPassword" class="form-control" placeholder="Password" />
                            </div>
                            <div class="col-md-12 col-lg-12">
                                <label for="txtConfirmPassword">Confirm Password: </label>
                                <input type="password" value="" id="txtConfirmPassword" name="txtConfirmPassword" class="form-control" placeholder="Password" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <button id="btnRegister" class="btn btn-success">Register !</button>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {

    <script type="text/javascript">

        $(document).ready(function () {

            $("#btnRegister").click(function () {

                if ($("#txtEmail").val().trim() == "") {
                    $("#lblMessageCorrectRegister").text("");
                    $("#dvRegisterCorrect").hide();
                    $("#lblMessageIncorrectRegister").text("You must enter an email !");
                    $("#dvRegisterIncorrect").toggle("slow");
                    return false;
                }

                if ($("#txtUsername").val().trim() == "") {
                    $("#lblMessageCorrectRegister").text("");
                    $("#dvRegisterCorrect").hide();
                    $("#lblMessageIncorrectRegister").text("You must enter an username !");
                    $("#dvRegisterIncorrect").toggle("slow");
                    return false;
                }

                if ($("#txtPassword").val().trim() == "") {
                    $("#lblMessageCorrectRegister").text("");
                    $("#dvRegisterCorrect").hide();
                    $("#lblMessageIncorrectRegister").text("You must enter a password !");
                    $("#dvRegisterIncorrect").toggle("slow");
                    return false;
                }

                if ($("#txtConfirmPassword").val().trim() == "") {
                    $("#lblMessageCorrectRegister").text("");
                    $("#dvRegisterCorrect").hide();
                    $("#lblMessageIncorrectRegister").text("You must confirm your password !");
                    $("#dvRegisterIncorrect").toggle("slow");
                    return false;
                }

                if ($("#txtPassword").val().trim() != $("#txtConfirmPassword").val().trim()) {
                    $("#lblMessageCorrectRegister").text("");
                    $("#dvRegisterCorrect").hide();
                    $("#lblMessageIncorrectRegister").text("Your password and confirm password must be the same !");
                    $("#dvRegisterIncorrect").toggle("slow");
                    return false;
                }

                var newUser = {
                    "Id": 0,
                    "Email": $("#txtEmail").val().trim(),
                    "Passwrd": $("#txtPassword").val().trim(),
                    "Username": $("#txtUsername").val().trim()
                }

                $.ajax({
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(newUser),
                    url: "@Url.Action("UserRegister")",
                    dataType: "json",
                    success: function (response) {
                        var responseData = response;
                        if (responseData.Code == "200") {
                            $("#lblMessageIncorrectRegister").text("");
                            $("#dvRegisterIncorrect").hide();
                            $("#lblMessageCorrectRegister").text("Register Success");
                            $("#dvRegisterCorrect").toggle("slow");
                        } else {
                            $("#lblMessageCorrectRegister").text("");
                            $("#dvRegisterCorrect").hide();
                            $("#lblMessageIncorrectRegister").text(responseData.Msg);
                            $("#dvRegisterIncorrect").toggle("slow");
                        }

                        setTimeout(function () {
                            $("#lblMessageCorrectRegister").text("");
                            $("#dvRegisterCorrect").hide();
                            $("#lblMessageIncorrectRegister").text("");
                            $("#dvRegisterIncorrect").hide();
                            $("#txtEmail").val("");
                            $("#txtUsername").val("");
                            $("#txtPassword").val("");
                            $("#txtConfirmPassword").val("");
                        }, 2000);
                    },
                    error: function (response) {
            
                    }
                });
            });

            $("#btnLogin").click(function () {

                if ($("#txtEmailLogin").val().trim() == "") {
                    $("#lblMessageCorrectLogin").text("");
                    $("#dvCorrectLogin").hide();
                    $("#lblMessageIncorrectLogin").text("You must enter an email !");
                    $("#dvIncorrectLogin").toggle("slow");
                    return false;
                }

                if ($("#txtPasswordLogin").val().trim() == "") {
                    $("#lblMessageCorrectLogin").text("");
                    $("#dvCorrectLogin").hide();
                    $("#lblMessageIncorrectLogin").text("You must enter an username !");
                    $("#dvIncorrectLogin").toggle("slow");
                    return false;
                }

                var user = {
                    "email": $("#txtEmailLogin").val().trim(),
                    "passwrd": $("#txtPasswordLogin").val().trim()
                }

                $.ajax({
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(user),
                    url: "@Url.Action("UserLogin")",
                    success: function (response) {
                        if (response.Code == 200) {
                            window.location.href = "@Url.Action("Index", "Chat")";
                        } else {
                            $("#lblMessageCorrectLogin").text("");
                            $("#dvCorrectLogin").hide();
                            $("#lblMessageIncorrectLogin").text(response.Msg);
                            $("#dvIncorrectLogin").toggle("slow");
                        }
                        
                    },
                    error: function (response) {
            
                    }
                });
            });

        });
        
    </script>

}

Chatroom/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>